name: Deploy Nutrition App to Azure

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/nutrition-app:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nutrition-app:${{ github.sha }}

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: nutrireg1768210400
          containerAppName: nutrition-app-prod
          resourceGroup: npl
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/nutrition-app:${{ github.sha }}
          location: francecentral